window.PROSPECT_SAVANT_DATA = Object.freeze({
  asOf: "2026-08-12",
  asOfLabel: "2026年8月12日",
  periodLabel: "2026年度累計",
  headline: {
    members: 1030,
    monthlyDelta: 3,
    admissionRate: 72.7,
    admissionPreviousRate: 68.5,
    admissionYoYDelta: 4.2,
    latestEventParticipants: 124,
  },
  comparison: {
    previousAsOf: "2026-08-11",
    previousAsOfLabel: "2026年8月11日",
    headline: {
      members: 1031,
      monthlyDelta: 4,
      admissionRate: 72.7,
      latestEventParticipants: 133,
    },
    teams: [
      { id: "A", rank: 1, members: 327, overall: 79, metrics: { retention: 81, admission: 88, event: 63, growth: 88, family: 68 } },
      { id: "B", rank: 2, members: 308, overall: 61, metrics: { retention: 48, admission: 63, event: 83, growth: 63, family: 63 } },
      { id: "C", rank: 3, members: 208, overall: 30, metrics: { retention: 17, admission: 38, event: 37, growth: 38, family: 29 } },
      { id: "D", rank: 4, members: 188, overall: 25, metrics: { retention: 33, admission: 13, event: 26, growth: 13, family: 38 } },
    ],
  },
  scoreGuide: [
    { value: 0, label: "LOW" },
    { value: 50, label: "AVERAGE" },
    { value: 80, label: "TOP 20%" },
    { value: 100, label: "ELITE" },
  ],
  weights: [
    { key: "retention", label: "定着力", value: 30 },
    { key: "admission", label: "年度入会力", value: 20 },
    { key: "growth", label: "成長力", value: 20 },
    { key: "event", label: "イベント力", value: 15 },
    { key: "family", label: "家庭継続力", value: 15 },
  ],
  metricLabels: {
    retention: "定着力",
    admission: "年度入会力",
    event: "イベント力",
    growth: "成長力",
    family: "家庭継続力",
  },
  teams: [
    {
      id: "A",
      rank: 1,
      members: 326,
      monthlyDelta: 16,
      overall: 79,
      status: "算出済",
      metrics: { retention: 81, admission: 88, event: 66, growth: 88, family: 68 },
      benchmark: {
        retention12mRate: 82.4,
        retention12mSample: 493,
        admissionRate: 86.0,
        admissionPreviousRate: 82.7,
        admissionYoYDelta: 3.3,
        eventRate: 16.7,
        repeatRate: 41.6,
      },
    },
    {
      id: "B",
      rank: 2,
      members: 308,
      monthlyDelta: 4,
      overall: 62,
      status: "算出済",
      metrics: { retention: 48, admission: 63, event: 86, growth: 63, family: 63 },
      benchmark: {
        retention12mRate: 79.3,
        retention12mSample: 387,
        admissionRate: 76.6,
        admissionPreviousRate: 80.6,
        admissionYoYDelta: -4.0,
        eventRate: 19.0,
        repeatRate: 46.1,
      },
    },
    {
      id: "C",
      rank: 3,
      members: 208,
      monthlyDelta: -14,
      overall: 30,
      status: "算出済",
      metrics: { retention: 17, admission: 38, event: 36, growth: 38, family: 29 },
      benchmark: {
        retention12mRate: 69.4,
        retention12mSample: 271,
        admissionRate: 63.8,
        admissionPreviousRate: 59.5,
        admissionYoYDelta: 4.2,
        eventRate: 9.1,
        repeatRate: 39.3,
      },
    },
    {
      id: "D",
      rank: 4,
      members: 188,
      monthlyDelta: -3,
      overall: 23,
      status: "参考値を含む",
      metrics: { retention: 33, admission: 13, event: 19, growth: 13, family: 38 },
      benchmark: {
        retention12mRate: 77.8,
        retention12mSample: 144,
        admissionRate: 57.9,
        admissionPreviousRate: 63.6,
        admissionYoYDelta: -5.7,
        eventRate: 7.4,
        repeatRate: 34.4,
      },
      note: "家庭継続力は評価対象が十分に蓄積するまで暫定です。",
    },
  ],
  methodology: [
    {
      title: "50が中央水準",
      body: "A〜Dの現在値だけで単純順位を付けず、比較可能な実績分布の中での位置をパーセンタイルで表示します。",
    },
    {
      title: "80は上位20％",
      body: "高得点をむやみに100へ揃えず、80以上は明確な強み、100はトップ水準として扱います。",
    },
    {
      title: "欠損は推測しない",
      body: "利用できない指標は除外し、利用可能な配点のみで比例換算します。参考値・推定値は明記します。",
    },
  ],
  quality: {
    completeness: 100,
    eventCount: 8,
    competitionCount: 2,
    competitionRows: 1068,
    note: "集計指標のみを掲載。会員個人情報・会場名・金額は公開データに含めていません。",
  },
});
